// Code generated by sqlc. DO NOT EDIT.
// source: contact_has_skill.sql

package db

import (
	"context"
)

const createContactHasSkill = `-- name: CreateContactHasSkill :one
INSERT INTO contact_has_skill (
  contact_id, 
  skill_id
) VALUES (
  $1, $2
)
RETURNING contact_id, skill_id
`

type CreateContactHasSkillParams struct {
	ContactID int32 `json:"contact_id"`
	SkillID   int32 `json:"skill_id"`
}

func (q *Queries) CreateContactHasSkill(ctx context.Context, arg CreateContactHasSkillParams) (ContactHasSkill, error) {
	row := q.db.QueryRowContext(ctx, createContactHasSkill, arg.ContactID, arg.SkillID)
	var i ContactHasSkill
	err := row.Scan(&i.ContactID, &i.SkillID)
	return i, err
}
