// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Contact struct {
	ID          int64  `json:"id"`
	Firstname   string `json:"firstname"`
	Lastname    string `json:"lastname"`
	Fullname    string `json:"fullname"`
	HomeAddress string `json:"home_address"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phone_number"`
}

type ContactHasSkill struct {
	ContactID int32 `json:"contact_id"`
	SkillID   int32 `json:"skill_id"`
}

type Skill struct {
	ID         int64          `json:"id"`
	SkillName  sql.NullString `json:"skill_name"`
	SkillLevel sql.NullString `json:"skill_level"`
}
