// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	CreateContactHasSkill(ctx context.Context, arg CreateContactHasSkillParams) (ContactHasSkill, error)
	CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error)
	DeleteContact(ctx context.Context, id int64) error
	DeleteSkill(ctx context.Context, id int64) error
	GetContact(ctx context.Context, id int64) (Contact, error)
	GetContactsWithSkill(ctx context.Context, skillName string) ([]Contact, error)
	GetContactsWithSkillAndLevel(ctx context.Context, arg GetContactsWithSkillAndLevelParams) ([]Contact, error)
	GetEmail(ctx context.Context, id int64) (string, error)
	GetFirstname(ctx context.Context, id int64) (string, error)
	GetFullname(ctx context.Context, id int64) (string, error)
	GetHomeAddress(ctx context.Context, id int64) (string, error)
	GetIfExistsID(ctx context.Context, id int64) (bool, error)
	GetLastname(ctx context.Context, id int64) (string, error)
	GetPhoneNumber(ctx context.Context, id int64) (string, error)
	GetSkill(ctx context.Context, id int64) (Skill, error)
	GetSkillLevel(ctx context.Context, id int64) (string, error)
	GetSkillName(ctx context.Context, id int64) (string, error)
	ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error)
	ListSkills(ctx context.Context, arg ListSkillsParams) ([]Skill, error)
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
	UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error)
}

var _ Querier = (*Queries)(nil)
