// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	CreateContactHasSkill(ctx context.Context, arg CreateContactHasSkillParams) (ContactHasSkill, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteContact(ctx context.Context, id int64) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteSkill(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, username string) error
	GetContact(ctx context.Context, id int64) (Contact, error)
	GetContactSkills(ctx context.Context, contactID int32) ([]Skill, error)
	GetContactsWithSkill(ctx context.Context, skillName string) ([]Contact, error)
	GetContactsWithSkillAndLevel(ctx context.Context, arg GetContactsWithSkillAndLevelParams) ([]Contact, error)
	GetEmail(ctx context.Context, id int64) (string, error)
	GetFirstname(ctx context.Context, id int64) (string, error)
	GetFullname(ctx context.Context, id int64) (string, error)
	GetHomeAddress(ctx context.Context, id int64) (string, error)
	GetIfExistsContactID(ctx context.Context, id int64) (bool, error)
	GetIfExistsSkillID(ctx context.Context, id int64) (bool, error)
	GetLastname(ctx context.Context, id int64) (string, error)
	GetPhoneNumber(ctx context.Context, id int64) (string, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetSkill(ctx context.Context, id int64) (Skill, error)
	GetSkillLevel(ctx context.Context, id int64) (string, error)
	GetSkillName(ctx context.Context, id int64) (string, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error)
	ListSkills(ctx context.Context, arg ListSkillsParams) ([]Skill, error)
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
	UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error)
}

var _ Querier = (*Queries)(nil)
